# Use an official Python image
FROM python

# Set working directory inside the container
WORKDIR /app

# Install system dependencies (optional but good for pip)
RUN apt-get update && apt-get install -y build-essential

# Copy local project files to container
COPY . .

# Install Python dependencies
RUN pip install --upgrade pip \
    && pip install -r requirements.txt

# Expose port 8000
EXPOSE 8000

# Command to run the app
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
